name: windows-arm

on:
  push:
    branches: ["windows-arm"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
        if: always()
      - run: python3 inspect.py
        if: always()
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
        if: always()
      - run: python3 inspect.py
        if: always()
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
        if: always()
      - run: uv run python inspect.py
        if: always()
