name: codesign

on:
  push:
    branches: ["codesign"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - run: |
          curl -LOJ https://github.com/astral-sh/python-build-standalone/releases/download/20250828/cpython-3.10.18+20250828-x86_64-apple-darwin-install_only_stripped.tar.gz
          tar xf cpython-3.10.18+20250828-x86_64-apple-darwin-install_only_stripped.tar.gz
          codesign -s - python/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so
      - uses: actions/upload-artifact@v4
        with:
          path: python/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so
