name: lol

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
      - name: Segfault
        run: uv run python -c 'import ctypes; ctypes.CDLL(None).strlen(1)'
      - name: something else
        run: echo hi
      - run: uv pip install pytest
      - run: ls -l $VIRTUAL_ENV/bin
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pytest
      - name: Report errors
        if: always()
        run: sudo dmesg
