name: release
on:
 push:
  branches: ["release"]
 workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        run: |
          gh release create potato --prerelease --title "Cool release" --notes tbd



